// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: "2025-07-15",
  devtools: { enabled: true },
  ssr: true,
  nitro: {
    preset: 'cloudflare-pages',
    prerender: {
      crawlLinks: true,
      routes: [
        "/",
        "/about",
        "/projects",
        "/skills",
        "/contact",
        // Rutas dinámicas de proyectos (IDs 1-27)
        "/project-detail/1",
        "/project-detail/2",
        "/project-detail/3",
        "/project-detail/4",
        "/project-detail/5",
        "/project-detail/6",
        "/project-detail/7",
        "/project-detail/8",
        "/project-detail/9",
        "/project-detail/10",
        "/project-detail/11",
        "/project-detail/12",
        "/project-detail/13",
        "/project-detail/14",
        "/project-detail/15",
        "/project-detail/16",
        "/project-detail/17",
        "/project-detail/18",
        "/project-detail/19",
        "/project-detail/20",
        "/project-detail/21",
        "/project-detail/22",
        "/project-detail/23",
        "/project-detail/24",
        "/project-detail/25",
        "/project-detail/26",
        "/project-detail/27",
      ],
      ignore: ["/project-detail/undefined"],
      failOnError: false,
    },
  },
  app: {
    pageTransition: { name: 'page', mode: 'out-in' },
    layoutTransition: { name: 'layout', mode: 'out-in' },
    head: {
      charset: 'utf-8',
      viewport: 'width=device-width, initial-scale=1',
      title: 'Julian.dev — Desarrollador Frontend',
      meta: [
        { name: 'description', content: 'Portfolio de Julian, desarrollador frontend especializado en Vue, Nuxt y animaciones web premium.' },
        { name: 'theme-color', content: '#0a0a0a' },
        { property: 'og:title', content: 'Julian.dev — Desarrollador Frontend' },
        { property: 'og:description', content: 'Portfolio de Julian, desarrollador frontend especializado en Vue, Nuxt y animaciones web premium.' },
        { property: 'og:type', content: 'website' },
        { name: 'twitter:card', content: 'summary_large_image' },
      ],
      link: [
        { rel: 'preconnect', href: 'https://fonts.googleapis.com' },
        { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' },
      ],
    }
  },
  css: ['~/assets/css/animations.css', '~/assets/css/main.css'],
  modules: [
    "@nuxt/icon",
    "@nuxtjs/tailwindcss",
    "@pinia/nuxt",
  ],
});