export interface EmojiItem {
  char: string;
  name: string;
  keywords: string[];
}

export interface EmojiCategory {
  id: string;
  name: string;
  icon: string;
  emojis: EmojiItem[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    name: 'Smileys & Emotion',
    icon: 'heroicons:face-smile',
    emojis: [
      { char: '😀', name: 'grinning face', keywords: ['happy', 'joy', 'smile', 'grin'] },
      { char: '😃', name: 'grinning face with big eyes', keywords: ['happy', 'joy', 'smile', 'haha'] },
      { char: '😄', name: 'grinning face with smiling eyes', keywords: ['happy', 'joy', 'smile', 'laugh'] },
      { char: '😁', name: 'beaming face with smiling eyes', keywords: ['happy', 'grin', 'smile'] },
      { char: '😆', name: 'grinning squinting face', keywords: ['happy', 'laugh', 'lol', 'haha'] },
      { char: '😅', name: 'grinning face with sweat', keywords: ['hot', 'nervous', 'laugh', 'relief'] },
      { char: '🤣', name: 'rolling on the floor laughing', keywords: ['lol', 'laugh', 'rofl', 'funny'] },
      { char: '😂', name: 'face with tears of joy', keywords: ['lol', 'laugh', 'cry', 'happy'] },
      { char: '🙂', name: 'slightly smiling face', keywords: ['smile', 'happy'] },
      { char: '🙃', name: 'upside-down face', keywords: ['silly', 'sarcasm', 'flip'] },
      { char: '😉', name: 'winking face', keywords: ['wink', 'flirt', 'joke'] },
      { char: '😊', name: 'smiling face with smiling eyes', keywords: ['happy', 'blush', 'smile'] },
      { char: '😇', name: 'smiling face with halo', keywords: ['angel', 'innocent', 'good'] },
      { char: '🥰', name: 'smiling face with hearts', keywords: ['love', 'affection', 'adorable'] },
      { char: '😍', name: 'smiling face with heart-eyes', keywords: ['love', 'crush', 'heart'] },
      { char: '🤩', name: 'star-struck', keywords: ['excited', 'star', 'wow'] },
      { char: '😘', name: 'face blowing a kiss', keywords: ['love', 'kiss', 'flirt'] },
      { char: '😗', name: 'kissing face', keywords: ['kiss', 'love'] },
      { char: '☺️', name: 'smiling face', keywords: ['smile', 'happy'] },
      { char: '😚', name: 'kissing face with closed eyes', keywords: ['kiss', 'love'] },
      { char: '😋', name: 'face savoring food', keywords: ['delicious', 'yum', 'hungry', 'tongue'] },
      { char: '😛', name: 'face with tongue', keywords: ['silly', 'tongue', 'playful'] },
      { char: '😜', name: 'winking face with tongue', keywords: ['silly', 'tongue', 'wink'] },
      { char: '🤪', name: 'zany face', keywords: ['crazy', 'silly', 'goofy'] },
      { char: '😝', name: 'squinting face with tongue', keywords: ['silly', 'tongue', 'playful'] },
      { char: '🤑', name: 'money-mouth face', keywords: ['money', 'rich', 'wealth'] },
      { char: '🤗', name: 'hugging face', keywords: ['hug', 'warm', 'friendly'] },
      { char: '🫣', name: 'face with peeking eye', keywords: ['peek', 'scared', 'hide'] },
      { char: '🤫', name: 'shushing face', keywords: ['quiet', 'shh', 'secret'] },
      { char: '🤔', name: 'thinking face', keywords: ['think', 'wonder', 'hmm'] },
      { char: '🫡', name: 'saluting face', keywords: ['salute', 'respect', 'yes'] },
      { char: '🤐', name: 'zipper-mouth face', keywords: ['silent', 'secret', 'hush'] },
      { char: '🤨', name: 'face with raised eyebrow', keywords: ['suspicious', 'hmm', 'skeptical'] },
      { char: '😐', name: 'neutral face', keywords: ['meh', 'neutral', 'deadpan'] },
      { char: '😑', name: 'expressionless face', keywords: ['meh', 'neutral', 'expressionless'] },
      { char: '😶', name: 'face without mouth', keywords: ['silent', 'quiet', 'speechless'] },
      { char: '🫥', name: 'dotted line face', keywords: ['invisible', 'disappear', 'neutral'] },
      { char: '😏', name: 'smirking face', keywords: ['smirk', 'sly', 'flirt'] },
      { char: '😒', name: 'unamused face', keywords: ['meh', 'bored', 'annoyed'] },
      { char: '🙄', name: 'face with rolling eyes', keywords: ['roll eyes', 'bored', 'annoyed'] },
      { char: '😬', name: 'grimacing face', keywords: ['grimace', 'awkward', 'nervous'] },
      { char: '🤥', name: 'lying face', keywords: ['lie', 'pinocchio'] },
      { char: '😌', name: 'relieved face', keywords: ['relieved', 'calm', 'peace'] },
      { char: '😔', name: 'pensive face', keywords: ['sad', 'pensive', 'sorry'] },
      { char: '😪', name: 'sleepy face', keywords: ['tired', 'sleep', 'sad'] },
      { char: '🤤', name: 'drooling face', keywords: ['drool', 'delicious', 'sleep'] },
      { char: '😴', name: 'sleeping face', keywords: ['sleep', 'zzz', 'tired'] },
      { char: '😷', name: 'face with medical mask', keywords: ['sick', 'mask', 'doctor'] },
      { char: '🤒', name: 'face with thermometer', keywords: ['sick', 'fever', 'cold'] },
      { char: '🤕', name: 'face with head-bandage', keywords: ['sick', 'hurt', 'injury'] },
      { char: '🤢', name: 'nauseated face', keywords: ['sick', 'disgust', 'vomit'] },
      { char: '🤮', name: 'face vomiting', keywords: ['sick', 'vomit', 'disgust'] },
      { char: '🤧', name: 'sneezing face', keywords: ['sick', 'cold', 'sneeze'] },
      { char: '🥵', name: 'hot face', keywords: ['hot', 'heat', 'sweat'] },
      { char: '🥶', name: 'cold face', keywords: ['cold', 'freeze', 'winter'] },
      { char: '🥴', name: 'woozy face', keywords: ['dizzy', 'drunk', 'woo'] },
      { char: '😵', name: 'face with crossed eyes', keywords: ['dizzy', 'dead', 'passed out'] },
      { char: '🤯', name: 'exploding head', keywords: ['mindblown', 'wow', 'crazy', 'mind'] },
      { char: '🤠', name: 'cowboy hat face', keywords: ['cowboy', 'hat', 'yeehaw'] },
      { char: '🥳', name: 'partying face', keywords: ['party', 'celebrate', 'birthday'] },
      { char: '😎', name: 'smiling face with sunglasses', keywords: ['cool', 'sunglasses', 'swag'] },
      { char: '🤓', name: 'nerd face', keywords: ['nerd', 'geek', 'smart'] },
      { char: '🧐', name: 'face with monocle', keywords: ['smart', 'inspect', 'monocle'] },
      { char: '😕', name: 'confused face', keywords: ['confused', 'huh'] },
      { char: '😟', name: 'worried face', keywords: ['worry', 'sad', 'nervous'] },
      { char: '🙁', name: 'slightly frowning face', keywords: ['sad', 'frown'] },
      { char: '😮', name: 'face with open mouth', keywords: ['wow', 'surprise', 'gasp'] },
      { char: '😯', name: 'hushed face', keywords: ['surprise', 'quiet', 'gasp'] },
      { char: '😲', name: 'astonished face', keywords: ['wow', 'surprise', 'gasp'] },
      { char: '😳', name: 'flushed face', keywords: ['blush', 'embarrassed', 'shy'] },
      { char: '🥺', name: 'pleading face', keywords: ['please', 'beg', 'puppy eyes'] },
      { char: '🥹', name: 'face holding back tears', keywords: ['cry', 'emotional', 'happy', 'grateful'] },
      { char: '😦', name: 'frowning face with open mouth', keywords: ['surprise', 'sad'] },
      { char: '😧', name: 'anguished face', keywords: ['surprise', 'sad', 'pain'] },
      { char: '😨', name: 'fearful face', keywords: ['scared', 'fear', 'gasp'] },
      { char: '😰', name: 'anxious face with sweat', keywords: ['scared', 'nervous', 'sweat'] },
      { char: '😱', name: 'face screaming in fear', keywords: ['scared', 'scream', 'fear'] },
      { char: '😭', name: 'loudly crying face', keywords: ['cry', 'sad', 'sob', 'crying'] },
      { char: '😓', name: 'downcast face with sweat', keywords: ['sad', 'nervous', 'sweat'] },
      { char: '😩', name: 'weary face', keywords: ['tired', 'weary', 'exhausted'] },
      { char: '😫', name: 'tired face', keywords: ['tired', 'exhausted'] },
      { char: '🥱', name: 'yawning face', keywords: ['tired', 'yawn', 'sleep'] },
      { char: '😤', name: 'face with steam from nose', keywords: ['angry', 'mad', 'frustrated'] },
      { char: '😡', name: 'enraged face', keywords: ['angry', 'mad', 'furious'] },
      { char: '😠', name: 'angry face', keywords: ['angry', 'mad'] },
      { char: '🤬', name: 'face with symbols on mouth', keywords: ['angry', 'swear', 'cuss'] },
      { char: '😈', name: 'smiling face with horns', keywords: ['devil', 'evil', 'mischievous'] },
      { char: '👿', name: 'angry face with horns', keywords: ['devil', 'evil', 'angry'] },
      { char: '💀', name: 'skull', keywords: ['dead', 'skeleton', 'lol'] },
      { char: '☠️', name: 'skull and crossbones', keywords: ['dead', 'danger', 'pirate'] },
      { char: '💩', name: 'pile of poo', keywords: ['poop', 'poo', 'silly'] },
      { char: '🤡', name: 'clown face', keywords: ['clown', 'silly', 'funny'] },
      { char: '👹', name: 'ogre', keywords: ['monster', 'scared', 'devil'] },
      { char: '👺', name: 'goblin', keywords: ['monster', 'evil'] },
      { char: '👻', name: 'ghost', keywords: ['scared', 'spooky', 'halloween'] },
      { char: '👽', name: 'alien', keywords: ['space', 'alien', 'sci-fi'] },
      { char: '👾', name: 'alien monster', keywords: ['retro', 'game', 'pixel'] },
      { char: '🤖', name: 'robot', keywords: ['bot', 'tech', 'ai'] }
    ]
  },
  {
    id: 'people',
    name: 'People & Body',
    icon: 'heroicons:user-group',
    emojis: [
      { char: '👋', name: 'waving hand', keywords: ['wave', 'hello', 'bye'] },
      { char: '🤚', name: 'raised back of hand', keywords: ['hand', 'stop'] },
      { char: '🖐️', name: 'hand with fingers splayed', keywords: ['hand', 'five'] },
      { char: '✋', name: 'raised hand', keywords: ['hand', 'stop', 'highfive'] },
      { char: '🖖', name: 'vulcan salute', keywords: ['spock', 'star trek', 'vulcan'] },
      { char: '🫱', name: 'rightwards hand', keywords: ['hand', 'shake'] },
      { char: '🫲', name: 'leftwards hand', keywords: ['hand', 'shake'] },
      { char: '🫳', name: 'palm down hand', keywords: ['hand', 'drop'] },
      { char: '🫴', name: 'palm up hand', keywords: ['hand', 'receive'] },
      { char: '👌', name: 'OK hand', keywords: ['ok', 'good', 'fine'] },
      { char: '🤌', name: 'pinched fingers', keywords: ['italian', 'gesture', 'what'] },
      { char: '🤏', name: 'pinched hand', keywords: ['small', 'little'] },
      { char: '✌️', name: 'victory hand', keywords: ['peace', 'two', 'victory'] },
      { char: '🤞', name: 'crossed fingers', keywords: ['luck', 'hope'] },
      { char: '🫰', name: 'hand with index finger and thumb crossed', keywords: ['heart', 'love', 'kpop'] },
      { char: '🤟', name: 'love-you gesture', keywords: ['love', 'gesture'] },
      { char: '🤘', name: 'sign of the horns', keywords: ['rock', 'metal', 'horns'] },
      { char: '🤙', name: 'call me hand', keywords: ['phone', 'shaka', 'call'] },
      { char: '👈', name: 'backhand index pointing left', keywords: ['point', 'left'] },
      { char: '👉', name: 'backhand index pointing right', keywords: ['point', 'right'] },
      { char: '👆', name: 'backhand index pointing up', keywords: ['point', 'up'] },
      { char: '🖕', name: 'middle finger', keywords: ['rude', 'finger'] },
      { char: '👇', name: 'backhand index pointing down', keywords: ['point', 'down'] },
      { char: '🫵', name: 'index pointing at the viewer', keywords: ['you', 'point'] },
      { char: '👍', name: 'thumbs up', keywords: ['like', 'good', 'yes', 'approve'] },
      { char: '👎', name: 'thumbs down', keywords: ['dislike', 'bad', 'no'] },
      { char: '✊', name: 'raised fist', keywords: ['fist', 'power', 'solidarity'] },
      { char: '👊', name: 'oncoming fist', keywords: ['fist', 'punch', 'brofist'] },
      { char: '🤛', name: 'left-facing fist', keywords: ['fist', 'punch'] },
      { char: '🤜', name: 'right-facing fist', keywords: ['fist', 'punch'] },
      { char: '👏', name: 'clapping hands', keywords: ['clap', 'applause', 'bravo'] },
      { char: '🙌', name: 'raising hands', keywords: ['celebrate', 'hooray', 'hands'] },
      { char: '🫶', name: 'heart hands', keywords: ['love', 'heart', 'affection'] },
      { char: '👐', name: 'open hands', keywords: ['hug', 'hands'] },
      { char: '🤲', name: 'palms up together', keywords: ['prayer', 'give'] },
      { char: '🤝', name: 'handshake', keywords: ['agree', 'deal', 'shake'] },
      { char: '🙏', name: 'folded hands', keywords: ['please', 'thank you', 'pray', 'hope'] },
      { char: '✍️', name: 'writing hand', keywords: ['write', 'pen', 'draw'] },
      { char: '💅', name: 'nail polish', keywords: ['nails', 'beauty', 'slay', 'sassy'] },
      { char: '🤳', name: 'selfie', keywords: ['selfie', 'phone', 'camera'] },
      { char: '💪', name: 'flexed biceps', keywords: ['muscle', 'strong', 'flex', 'gym'] },
      { char: '🦾', name: 'mechanical arm', keywords: ['robot', 'cybernetic'] },
      { char: '🦿', name: 'mechanical leg', keywords: ['robot', 'cybernetic'] },
      { char: '🦵', name: 'leg', keywords: ['kick', 'limb'] },
      { char: '🦶', name: 'foot', keywords: ['kick', 'walk'] },
      { char: '👂', name: 'ear', keywords: ['listen', 'hear'] },
      { char: '🦻', name: 'ear with hearing aid', keywords: ['deaf', 'accessible'] },
      { char: '👃', name: 'nose', keywords: ['smell', 'sniff'] },
      { char: '🧠', name: 'brain', keywords: ['think', 'smart', 'mind'] },
      { char: '🫀', name: 'anatomical heart', keywords: ['heart', 'cardio', 'organ'] },
      { char: '🫁', name: 'lungs', keywords: ['breathe', 'organ'] },
      { char: '🦷', name: 'tooth', keywords: ['dentist', 'teeth'] },
      { char: '🦴', name: 'bone', keywords: ['skeleton'] },
      { char: '👀', name: 'eyes', keywords: ['look', 'see', 'watch'] },
      { char: '👁️', name: 'eye', keywords: ['look', 'see'] },
      { char: '👅', name: 'tongue', keywords: ['tongue', 'taste'] },
      { char: '👄', name: 'mouth', keywords: ['lips', 'kiss'] },
      { char: '💋', name: 'kiss mark', keywords: ['lips', 'kiss', 'love'] }
    ]
  },
  {
    id: 'nature',
    name: 'Animals & Nature',
    icon: 'heroicons:sparkles',
    emojis: [
      { char: '🙈', name: 'see-no-evil monkey', keywords: ['monkey', 'blind', 'shy'] },
      { char: '🙉', name: 'hear-no-evil monkey', keywords: ['monkey', 'deaf', 'secret'] },
      { char: '🙊', name: 'speak-no-evil monkey', keywords: ['monkey', 'mute', 'shh'] },
      { char: '💥', name: 'collision', keywords: ['explode', 'bang', 'boom'] },
      { char: '🐵', name: 'monkey face', keywords: ['monkey', 'animal'] },
      { char: '🐒', name: 'monkey', keywords: ['monkey', 'animal'] },
      { char: '🦍', name: 'gorilla', keywords: ['gorilla', 'animal'] },
      { char: '🦧', name: 'orangutan', keywords: ['orangutan', 'animal'] },
      { char: '🐶', name: 'dog face', keywords: ['dog', 'puppy', 'pet', 'animal'] },
      { char: '🐕', name: 'dog', keywords: ['dog', 'animal'] },
      { char: '🦮', name: 'guide dog', keywords: ['dog', 'blind'] },
      { char: '🐕‍🦺', name: 'service dog', keywords: ['dog', 'service'] },
      { char: '🐩', name: 'poodle', keywords: ['dog', 'animal'] },
      { char: '🐺', name: 'wolf', keywords: ['wolf', 'animal'] },
      { char: '🦊', name: 'fox', keywords: ['fox', 'animal'] },
      { char: '🦝', name: 'raccoon', keywords: ['raccoon', 'animal'] },
      { char: '🐱', name: 'cat face', keywords: ['cat', 'kitten', 'pet', 'animal'] },
      { char: '🐈', name: 'cat', keywords: ['cat', 'animal'] },
      { char: '🐈‍⬛', name: 'black cat', keywords: ['cat', 'black'] },
      { char: '🦁', name: 'lion', keywords: ['lion', 'animal'] },
      { char: '🐯', name: 'tiger face', keywords: ['tiger', 'animal'] },
      { char: '🐆', name: 'leopard', keywords: ['leopard', 'animal'] },
      { char: '🐴', name: 'horse face', keywords: ['horse', 'animal'] },
      { char: '🫎', name: 'moose', keywords: ['moose', 'animal'] },
      { char: '🫏', name: 'donkey', keywords: ['donkey', 'animal'] },
      { char: '🦄', name: 'unicorn', keywords: ['unicorn', 'magic'] },
      { char: '🐮', name: 'cow face', keywords: ['cow', 'animal'] },
      { char: '🐷', name: 'pig face', keywords: ['pig', 'animal'] },
      { char: '🐑', name: 'ewe', keywords: ['sheep', 'animal'] },
      { char: '🐐', name: 'goat', keywords: ['goat', 'animal'] },
      { char: '🐪', name: 'camel', keywords: ['camel', 'animal'] },
      { char: '🦒', name: 'giraffe', keywords: ['giraffe', 'animal'] },
      { char: '🐘', name: 'elephant', keywords: ['elephant', 'animal'] },
      { char: '🦣', name: 'mammoth', keywords: ['mammoth', 'animal'] },
      { char: '🦏', name: 'rhinoceros', keywords: ['rhino', 'animal'] },
      { char: '🦛', name: 'hippopotamus', keywords: ['hippo', 'animal'] },
      { char: '🐭', name: 'mouse face', keywords: ['mouse', 'animal'] },
      { char: '🐰', name: 'rabbit face', keywords: ['rabbit', 'bunny', 'animal'] },
      { char: '🐿️', name: 'chipmunk', keywords: ['chipmunk', 'animal'] },
      { char: '🦫', name: 'beaver', keywords: ['beaver', 'animal'] },
      { char: '🦔', name: 'hedgehog', keywords: ['hedgehog', 'animal'] },
      { char: '🦇', name: 'bat', keywords: ['bat', 'vampire', 'animal'] },
      { char: '🐻', name: 'bear', keywords: ['bear', 'animal'] },
      { char: '🐨', name: 'koala', keywords: ['koala', 'animal'] },
      { char: '🐼', name: 'panda', keywords: ['panda', 'animal'] },
      { char: '🦥', name: 'sloth', keywords: ['sloth', 'slow', 'animal'] },
      { char: '🦦', name: 'otter', keywords: ['otter', 'animal'] },
      { char: '🦨', name: 'skunk', keywords: ['skunk', 'animal'] },
      { char: '🦘', name: 'kangaroo', keywords: ['kangaroo', 'animal'] },
      { char: '🦡', name: 'badger', keywords: ['badger', 'animal'] },
      { char: '🦅', name: 'eagle', keywords: ['eagle', 'bird', 'animal'] },
      { char: '🦆', name: 'duck', keywords: ['duck', 'bird', 'animal'] },
      { char: '🐦', name: 'bird', keywords: ['bird', 'animal'] },
      { char: '🐧', name: 'penguin', keywords: ['penguin', 'bird', 'animal'] },
      { char: '🦉', name: 'owl', keywords: ['owl', 'bird', 'animal'] },
      { char: '🦈', name: 'shark', keywords: ['shark', 'fish', 'ocean', 'animal'] },
      { char: '🐬', name: 'dolphin', keywords: ['dolphin', 'ocean', 'animal'] },
      { char: '🐙', name: 'octopus', keywords: ['octopus', 'ocean', 'animal'] },
      { char: '🦞', name: 'lobster', keywords: ['lobster', 'seafood', 'animal'] },
      { char: '🦐', name: 'shrimp', keywords: ['shrimp', 'seafood', 'animal'] },
      { char: '🦑', name: 'squid', keywords: ['squid', 'ocean', 'animal'] },
      { char: '🦋', name: 'butterfly', keywords: ['butterfly', 'insect', 'animal'] },
      { char: '🐝', name: 'honeybee', keywords: ['bee', 'bug', 'insect'] },
      { char: '🐞', name: 'lady beetle', keywords: ['ladybug', 'bug', 'insect'] },
      { char: '🕷️', name: 'spider', keywords: ['spider', 'bug', 'halloween'] },
      { char: '🕸️', name: 'spider web', keywords: ['web', 'spooky', 'halloween'] },
      { char: 'Scorpion', name: 'scorpion', keywords: ['scorpion', 'bug', 'scorpio'] },
      { char: '🔥', name: 'fire', keywords: ['hot', 'flame', 'lit', 'burn'] },
      { char: '✨', name: 'sparkles', keywords: ['sparkle', 'magic', 'shine', 'glow'] },
      { char: '⭐', name: 'star', keywords: ['star', 'gold'] },
      { char: '🌈', name: 'rainbow', keywords: ['rainbow', 'color', 'pride'] },
      { char: '⚡', name: 'high voltage', keywords: ['lightning', 'thunder', 'power'] },
      { char: '☄️', name: 'comet', keywords: ['comet', 'space'] },
      { char: '☀️', name: 'sun', keywords: ['sun', 'sunny', 'weather', 'hot'] },
      { char: '🌤️', name: 'sun behind small cloud', keywords: ['weather', 'cloudy'] },
      { char: '⛅', name: 'sun behind cloud', keywords: ['weather', 'cloudy'] },
      { char: '☁️', name: 'cloud', keywords: ['weather', 'cloudy'] },
      { char: '🌧️', name: 'cloud with rain', keywords: ['weather', 'rain', 'wet'] },
      { char: '⛈️', name: 'cloud with lightning and rain', keywords: ['weather', 'thunderstorm'] },
      { char: '❄️', name: 'snowflake', keywords: ['weather', 'snow', 'cold', 'winter'] },
      { char: '💨', name: 'dashing away', keywords: ['wind', 'fast', 'run', 'smoke'] },
      { char: '💧', name: 'droplet', keywords: ['water', 'drip', 'wet'] },
      { char: '💦', name: 'sweat droplets', keywords: ['sweat', 'water', 'splash'] },
      { char: '🌊', name: 'water wave', keywords: ['wave', 'ocean', 'sea', 'beach'] }
    ]
  },
  {
    id: 'food',
    name: 'Food & Drink',
    icon: 'heroicons:cake',
    emojis: [
      { char: '🍏', name: 'green apple', keywords: ['apple', 'fruit', 'food'] },
      { char: '🍎', name: 'red apple', keywords: ['apple', 'fruit', 'food'] },
      { char: '🍐', name: 'pear', keywords: ['pear', 'fruit', 'food'] },
      { char: '🍊', name: 'tangerine', keywords: ['orange', 'citrus', 'fruit'] },
      { char: '🍋', name: 'lemon', keywords: ['lemon', 'citrus', 'fruit'] },
      { char: '🍌', name: 'banana', keywords: ['banana', 'fruit'] },
      { char: '🍉', name: 'watermelon', keywords: ['watermelon', 'fruit'] },
      { char: '🍇', name: 'grapes', keywords: ['grape', 'fruit', 'wine'] },
      { char: '🍓', name: 'strawberry', keywords: ['berry', 'strawberry', 'fruit'] },
      { char: '🫐', name: 'blueberries', keywords: ['berry', 'blueberry'] },
      { char: '🍈', name: 'melon', keywords: ['melon', 'fruit'] },
      { char: '🍒', name: 'cherries', keywords: ['cherry', 'fruit'] },
      { char: '🍑', name: 'peach', keywords: ['peach', 'fruit'] },
      { char: '🍑', name: 'peach', keywords: ['peach', 'fruit'] },
      { char: '🍍', name: 'pineapple', keywords: ['pineapple', 'fruit'] },
      { char: '🥥', name: 'coconut', keywords: ['coconut', 'fruit'] },
      { char: '🥝', name: 'kiwi fruit', keywords: ['kiwi', 'fruit'] },
      { char: '🍅', name: 'tomato', keywords: ['tomato', 'vegetable'] },
      { char: '🥑', name: 'avocado', keywords: ['avocado', 'guac'] },
      { char: '🍆', name: 'eggplant', keywords: ['eggplant', 'vegetable'] },
      { char: '🥔', name: 'potato', keywords: ['potato', 'carb'] },
      { char: '🥕', name: 'carrot', keywords: ['carrot', 'vegetable'] },
      { char: '🌽', name: 'ear of corn', keywords: ['corn', 'vegetable'] },
      { char: '🌶️', name: 'hot pepper', keywords: ['spicy', 'chili', 'hot'] },
      { char: '🫑', name: 'bell pepper', keywords: ['pepper', 'vegetable'] },
      { char: '🍄', name: 'mushroom', keywords: ['mushroom', 'fungus'] },
      { char: '🧅', name: 'onion', keywords: ['onion', 'garlic'] },
      { char: '🥦', name: 'broccoli', keywords: ['broccoli', 'vegetable'] },
      { char: '🥬', name: 'leafy green', keywords: ['lettuce', 'salad'] },
      { char: '🍕', name: 'pizza', keywords: ['pizza', 'fast food', 'cheese'] },
      { char: '🍔', name: 'hamburger', keywords: ['burger', 'fast food', 'meat'] },
      { char: '🍟', name: 'french fries', keywords: ['fries', 'fast food', 'potato'] },
      { char: '🌭', name: 'hot dog', keywords: ['hotdog', 'fast food'] },
      { char: '🌮', name: 'taco', keywords: ['taco', 'mexican'] },
      { char: '🌯', name: 'burrito', keywords: ['burrito', 'mexican'] },
      { char: '🍳', name: 'cooking', keywords: ['egg', 'breakfast', 'cook'] },
      { char: '🍿', name: 'popcorn', keywords: ['popcorn', 'movie', 'snack'] },
      { char: '🍩', name: 'donut', keywords: ['donut', 'sweet', 'dessert'] },
      { char: '🍪', name: 'cookie', keywords: ['cookie', 'sweet', 'snack'] },
      { char: '🎂', name: 'birthday cake', keywords: ['cake', 'birthday', 'celebrate'] },
      { char: '🍰', name: 'shortcake', keywords: ['cake', 'sweet', 'dessert'] },
      { char: '🧁', name: 'cupcake', keywords: ['cupcake', 'sweet', 'dessert'] },
      { char: '🍫', name: 'chocolate bar', keywords: ['chocolate', 'sweet', 'candy'] },
      { char: '🍬', name: 'candy', keywords: ['candy', 'sweet'] },
      { char: '🍭', name: 'lollipop', keywords: ['lollipop', 'sweet', 'candy'] },
      { char: '🍦', name: 'soft ice cream', keywords: ['ice cream', 'sweet', 'dessert'] },
      { char: '🍧', name: 'shaved ice', keywords: ['ice', 'sweet'] },
      { char: '🍨', name: 'ice cream', keywords: ['ice cream', 'sweet'] },
      { char: '🍺', name: 'beer mug', keywords: ['beer', 'drink', 'alcohol', 'bar'] },
      { char: '🍻', name: 'clinking beer mugs', keywords: ['beer', 'drinks', 'alcohol', 'cheers'] },
      { char: '🥂', name: 'clinking glasses', keywords: ['champagne', 'drinks', 'cheers', 'toast'] },
      { char: '🍷', name: 'wine glass', keywords: ['wine', 'alcohol', 'drink'] },
      { char: '🥃', name: 'tumbler glass', keywords: ['whiskey', 'alcohol', 'drink'] },
      { char: '🍸', name: 'cocktail glass', keywords: ['cocktail', 'martini', 'drink'] },
      { char: '🍹', name: 'tropical drink', keywords: ['cocktail', 'tropical', 'beach'] },
      { char: '☕', name: 'hot beverage', keywords: ['coffee', 'tea', 'cafe', 'hot'] },
      { char: '🍵', name: 'teacup without handle', keywords: ['tea', 'matcha', 'green tea'] },
      { char: '🥤', name: 'cup with straw', keywords: ['soda', 'drink', 'juice'] },
      { char: '🧃', name: 'beverage box', keywords: ['juice', 'drink'] },
      { char: '🥛', name: 'glass of milk', keywords: ['milk', 'drink'] }
    ]
  },
  {
    id: 'activities',
    name: 'Activities',
    icon: 'heroicons:trophy',
    emojis: [
      { char: '🎈', name: 'balloon', keywords: ['balloon', 'party', 'celebrate'] },
      { char: '🎉', name: 'party popper', keywords: ['celebrate', 'party', 'congrats'] },
      { char: '🎊', name: 'confetti ball', keywords: ['celebrate', 'party', 'congrats'] },
      { char: '🏆', name: 'trophy', keywords: ['win', 'prize', 'award', 'trophy'] },
      { char: '🥇', name: '1st place medal', keywords: ['win', 'gold', 'medal'] },
      { char: '🥈', name: '2nd place medal', keywords: ['silver', 'medal'] },
      { char: '🥉', name: '3rd place medal', keywords: ['bronze', 'medal'] },
      { char: '🏅', name: 'sports medal', keywords: ['medal', 'sports'] },
      { char: '🎖️', name: 'military medal', keywords: ['medal', 'military'] },
      { char: '🎗️', name: 'reminder ribbon', keywords: ['ribbon', 'awareness'] },
      { char: '🎫', name: 'ticket', keywords: ['ticket', 'event', 'show'] },
      { char: '🎟️', name: 'admission tickets', keywords: ['ticket', 'event', 'movie'] },
      { char: '⚽', name: 'soccer ball', keywords: ['soccer', 'football', 'sports', 'ball'] },
      { char: '🏀', name: 'basketball', keywords: ['basketball', 'sports', 'ball'] },
      { char: '🏈', name: 'american football', keywords: ['football', 'sports', 'ball'] },
      { char: '⚾', name: 'baseball', keywords: ['baseball', 'sports', 'ball'] },
      { char: '🥎', name: 'softball', keywords: ['softball', 'sports', 'ball'] },
      { char: '🎾', name: 'tennis', keywords: ['tennis', 'sports', 'racket', 'ball'] },
      { char: '🏐', name: 'volleyball', keywords: ['volleyball', 'sports', 'ball'] },
      { char: '🏉', name: 'rugby football', keywords: ['rugby', 'sports', 'ball'] },
      { char: '🥏', name: 'frisbee', keywords: ['frisbee', 'sports'] },
      { char: '🎱', name: 'billiard', keywords: ['pool', 'billiards', '8ball', 'game'] },
      { char: '🪀', name: 'yo-yo', keywords: ['yoyo', 'toy'] },
      { char: '🏓', name: 'ping pong', keywords: ['table tennis', 'sports', 'game'] },
      { char: '🏸', name: 'badminton', keywords: ['badminton', 'sports'] },
      { char: '🥅', name: 'goal net', keywords: ['net', 'goal', 'soccer'] },
      { char: '⛳', name: 'flag in hole', keywords: ['golf', 'sports'] },
      { char: '🏹', name: 'bow and arrow', keywords: ['archery', 'arrow'] },
      { char: '🎣', name: 'fishing pole', keywords: ['fish', 'fishing'] },
      { char: '🤿', name: 'diving mask', keywords: ['scuba', 'swim'] },
      { char: '🥊', name: 'boxing glove', keywords: ['box', 'boxing', 'fight'] },
      { char: '🥋', name: 'martial arts uniform', keywords: ['karate', 'judo', 'fight'] },
      { char: '🎽', name: 'running shirt', keywords: ['run', 'track'] },
      { char: ' skateboard', name: 'skateboard', keywords: ['skate', 'board'] },
      { char: '🛼', name: 'roller skate', keywords: ['skate', 'roller'] },
      { char: '🛷', name: 'sled', keywords: ['sleigh', 'snow'] },
      { char: '⛸️', name: 'ice skate', keywords: ['skate', 'ice', 'snow'] },
      { char: '🥌', name: 'curling stone', keywords: ['curling', 'stone'] },
      { char: '🎯', name: 'bullseye', keywords: ['darts', 'target', 'aim', 'goal'] },
      { char: '🪗', name: 'accordion', keywords: ['music', 'instrument'] },
      { char: '🎮', name: 'video game', keywords: ['game', 'controller', 'playstation', 'xbox', 'switch'] },
      { char: '🎰', name: 'slot machine', keywords: ['casino', 'slots', 'gamble'] },
      { char: '🎲', name: 'game die', keywords: ['dice', 'game', 'boardgame'] },
      { char: '🧩', name: 'puzzle piece', keywords: ['puzzle', 'jigsaw'] },
      { char: '🧸', name: 'teddy bear', keywords: ['toy', 'bear'] },
      { char: '🪅', name: 'piñata', keywords: ['pinata', 'party'] },
      { char: '🪩', name: 'mirror ball', keywords: ['disco', 'party', 'dance'] },
      { char: '🪄', name: 'magic wand', keywords: ['magic', 'wand', 'wizard'] }
    ]
  },
  {
    id: 'travel',
    name: 'Travel & Places',
    icon: 'heroicons:map-pin',
    emojis: [
      { char: '🚗', name: 'automobile', keywords: ['car', 'drive', 'travel'] },
      { char: '🚕', name: 'taxi', keywords: ['cab', 'taxi', 'drive'] },
      { char: '🚙', name: 'sport utility vehicle', keywords: ['car', 'drive'] },
      { char: '🚌', name: 'bus', keywords: ['bus', 'transit', 'drive'] },
      { char: '🚎', name: 'trolleybus', keywords: ['bus', 'transit'] },
      { char: '🏎️', name: 'racing car', keywords: ['race', 'car', 'f1'] },
      { char: '🚓', name: 'police car', keywords: ['police', 'cop', 'car'] },
      { char: '🚑', name: 'ambulance', keywords: ['ambulance', 'hospital', 'er'] },
      { char: '🚒', name: 'fire engine', keywords: ['fire', 'truck'] },
      { char: '🚐', name: 'minibus', keywords: ['van', 'bus'] },
      { char: '🚚', name: 'delivery truck', keywords: ['truck', 'deliver', 'mover'] },
      { char: '🚛', name: 'articulated lorry', keywords: ['truck', 'semi'] },
      { char: '🚜', name: 'tractor', keywords: ['tractor', 'farm'] },
      { char: '🚲', name: 'bicycle', keywords: ['bike', 'cycle', 'ride'] },
      { char: '🛵', name: 'motor scooter', keywords: ['scooter', 'vespa', 'ride'] },
      { char: '🏍️', name: 'motorcycle', keywords: ['motorcycle', 'bike', 'ride'] },
      { char: '🛺', name: 'auto rickshaw', keywords: ['rickshaw', 'tuk tuk'] },
      { char: '🚨', name: 'police car light', keywords: ['alarm', 'siren', 'emergency'] },
      { char: '✈️', name: 'airplane', keywords: ['plane', 'fly', 'travel', 'flight'] },
      { char: '🛫', name: 'airplane departure', keywords: ['takeoff', 'plane', 'travel'] },
      { char: '🛬', name: 'airplane arrival', keywords: ['landing', 'plane', 'travel'] },
      { char: '🛸', name: 'flying saucer', keywords: ['ufo', 'alien', 'space'] },
      { char: '🚀', name: 'rocket', keywords: ['rocket', 'space', 'launch', 'startup'] },
      { char: '🚁', name: 'helicopter', keywords: ['chopper', 'fly'] },
      { char: '🛶', name: 'canoe', keywords: ['boat', 'kayak'] },
      { char: '⛵', name: 'sailboat', keywords: ['boat', 'sail'] },
      { char: '🛥️', name: 'motorboat', keywords: ['boat', 'yacht'] },
      { char: '🚢', name: 'ship', keywords: ['boat', 'cruise', 'sea'] },
      { char: '⚓', name: 'anchor', keywords: ['anchor', 'boat', 'sea'] },
      { char: '⛽', name: 'fuel pump', keywords: ['gas', 'fuel'] },
      { char: '🚧', name: 'construction', keywords: ['caution', 'warning', 'road'] },
      { char: '🗺️', name: 'world map', keywords: ['map', 'travel', 'guide'] },
      { char: '🗽', name: 'Statue of Liberty', keywords: ['nyc', 'america', 'statue'] },
      { char: '🗼', name: 'Tokyo tower', keywords: ['tokyo', 'japan', 'tower'] },
      { char: '🏰', name: 'castle', keywords: ['castle', 'royal'] },
      { char: '🏯', name: 'Japanese castle', keywords: ['castle', 'japan'] },
      { char: '🏟️', name: 'stadium', keywords: ['stadium', 'sports', 'concert'] },
      { char: '🎡', name: 'Ferris wheel', keywords: ['ferris wheel', 'carnival', 'park'] },
      { char: '🎢', name: 'roller coaster', keywords: ['coaster', 'thrill', 'park'] },
      { char: '🎪', name: 'circus tent', keywords: ['circus', 'tent'] },
      { char: '⛲', name: 'fountain', keywords: ['fountain', 'park'] },
      { char: '🏖️', name: 'beach with umbrella', keywords: ['beach', 'vacation', 'summer'] },
      { char: '🏜️', name: 'desert', keywords: ['desert', 'hot'] },
      { char: '🌋', name: 'volcano', keywords: ['volcano', 'lava'] },
      { char: '🗻', name: 'Mount Fuji', keywords: ['fuji', 'mountain', 'japan'] }
    ]
  },
  {
    id: 'objects',
    name: 'Objects',
    icon: 'heroicons:light-bulb',
    emojis: [
      { char: '💡', name: 'light bulb', keywords: ['idea', 'light', 'bright', 'smart'] },
      { char: '💻', name: 'laptop', keywords: ['computer', 'laptop', 'tech', 'screen', 'coding'] },
      { char: '🖥️', name: 'desktop computer', keywords: ['computer', 'screen', 'desktop'] },
      { char: '🖨️', name: 'printer', keywords: ['print', 'office'] },
      { char: '鼠标', name: 'computer mouse', keywords: ['mouse', 'click', 'computer'] },
      { char: '🔌', name: 'electric plug', keywords: ['plug', 'electricity', 'charge'] },
      { char: '🔋', name: 'battery', keywords: ['battery', 'charge', 'power'] },
      { char: '💾', name: 'floppy disk', keywords: ['save', 'disk', 'retro'] },
      { char: '💿', name: 'optical disk', keywords: ['cd', 'dvd', 'disc'] },
      { char: '🎥', name: 'movie camera', keywords: ['camera', 'movie', 'film'] },
      { char: '🎬', name: 'clapper board', keywords: ['clapper', 'movie', 'film'] },
      { char: '📺', name: 'television', keywords: ['tv', 'screen'] },
      { char: '📷', name: 'camera', keywords: ['camera', 'photo'] },
      { char: '📸', name: 'camera with flash', keywords: ['camera', 'photo', 'flash'] },
      { char: '🔍', name: 'magnifying glass tilted left', keywords: ['search', 'find', 'zoom'] },
      { char: '🕯️', name: 'candle', keywords: ['light', 'candle', 'spooky'] },
      { char: '🔦', name: 'flashlight', keywords: ['light', 'torch'] },
      { char: '📔', name: 'notebook with decorative cover', keywords: ['book', 'notebook'] },
      { char: '📕', name: 'closed book', keywords: ['book', 'read'] },
      { char: '📖', name: 'open book', keywords: ['book', 'read', 'learn'] },
      { char: '📚', name: 'books', keywords: ['books', 'library', 'study', 'read'] },
      { char: '📝', name: 'memo', keywords: ['write', 'note', 'paper'] },
      { char: '📁', name: 'file folder', keywords: ['folder', 'file'] },
      { char: '📂', name: 'open file folder', keywords: ['folder', 'file'] },
      { char: '📅', name: 'calendar', keywords: ['calendar', 'date'] },
      { char: '📈', name: 'chart increasing', keywords: ['chart', 'grow', 'graph'] },
      { char: '📉', name: 'chart decreasing', keywords: ['chart', 'loss', 'graph'] },
      { char: '📊', name: 'bar chart', keywords: ['chart', 'graph'] },
      { char: '📌', name: 'pushpin', keywords: ['pin', 'map'] },
      { char: '📍', name: 'round pushpin', keywords: ['pin', 'map'] },
      { char: '📎', name: 'paperclip', keywords: ['clip', 'paper'] },
      { char: '✂️', name: 'scissors', keywords: ['cut', 'scissors'] },
      { char: '🔒', name: 'locked', keywords: ['lock', 'secure', 'private'] },
      { char: '🔓', name: 'unlocked', keywords: ['lock', 'open'] },
      { char: '🔑', name: 'key', keywords: ['key', 'secret', 'password'] },
      { char: '🔨', name: 'hammer', keywords: ['tool', 'hammer', 'build'] },
      { char: '🔧', name: 'wrench', keywords: ['tool', 'wrench', 'fix'] },
      { char: '⚙️', name: 'gear', keywords: ['cog', 'settings', 'gear'] },
      { char: '🧪', name: 'test tube', keywords: ['science', 'chemistry', 'lab'] },
      { char: '🧬', name: 'dna', keywords: ['science', 'biology', 'gene'] },
      { char: '🔬', name: 'microscope', keywords: ['science', 'lab', 'zoom'] },
      { char: '🔭', name: 'telescope', keywords: ['science', 'space', 'star'] }
    ]
  },
  {
    id: 'symbols',
    name: 'Symbols',
    icon: 'heroicons:hashtag',
    emojis: [
      { char: '❤️', name: 'red heart', keywords: ['love', 'heart', 'affection'] },
      { char: '🧡', name: 'orange heart', keywords: ['love', 'heart'] },
      { char: '💛', name: 'yellow heart', keywords: ['love', 'heart'] },
      { char: '💚', name: 'green heart', keywords: ['love', 'heart'] },
      { char: '💙', name: 'blue heart', keywords: ['love', 'heart'] },
      { char: '💜', name: 'purple heart', keywords: ['love', 'heart'] },
      { char: '🖤', name: 'black heart', keywords: ['love', 'heart'] },
      { char: '🤍', name: 'white heart', keywords: ['love', 'heart'] },
      { char: '💔', name: 'broken heart', keywords: ['sad', 'breakup', 'heart'] },
      { char: '❤️‍🔥', name: 'heart on fire', keywords: ['love', 'passionate', 'hot'] },
      { char: '💕', name: 'two hearts', keywords: ['love', 'hearts'] },
      { char: '💞', name: 'revolving hearts', keywords: ['love', 'hearts'] },
      { char: '✨', name: 'sparkles', keywords: ['sparkle', 'magic'] },
      { char: '⭐', name: 'star', keywords: ['star'] },
      { char: '🌟', name: 'glowing star', keywords: ['star', 'glow'] },
      { char: '❗', name: 'exclamation mark', keywords: ['alert', 'warning', 'danger'] },
      { char: '❓', name: 'question mark', keywords: ['question', 'confused'] },
      { char: '💯', name: 'hundred points', keywords: ['100', 'perfect', 'score'] }
    ]
  }
];
